### ISSUE TITLE
Find a way to end the dashboard Thread with "Mesa" backend

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [Met4FoF/agentMET4FOF#163]
The dashboard for the _osbrain_ backend is of type _Process_, which provides the `terminate()` method, whereas the _mesa_ dashboard is of type _Thread_. _Thread_ does not provide any means of stopping itself, so we actually need to implement something maybe based on [this recipe](https://www.oreilly.com/library/view/python-cookbook/0596001673/ch06s03.html).

**Comment by BjoernLudwigPTB** [comment]
This is actually not resolved. We only ensured proper termination of the `shutdown()` method of the instantiated AgentNetwork class, but the agents are actually still running in the back. That's what we try to resolve in #170.

**Comment by BjoernLudwigPTB** [comment]
The residing issues can probably solve as hinted here:

- https://stackoverflow.com/questions/58295145/stopping-the-mesa-server
- https://stackoverflow.com/questions/5375220/how-do-i-stop-tornado-web-server

**Comment by bangxiangyong** [comment]
To stop the mesa agents, we need to stop/remove the timer defined in the _AgentController() at https://github.com/Met4FoF/agentMET4FOF/blob/develop/agentMET4FOF/agents.py
`def start_mesa_timer(self, mesa_update_interval):`. So the `_AgentController` should be deleted/terminated along with the shutdown of AgentNetwork.

In the mesa backend, there's only one real timer which is started by the _AgentController which holds all the agents created in the MesaModel object, and every timer tick will advance the agent actions (see `step()` which calls agent_loop and on_received_message). <- we should put this in a documentation , perhaps a tutorial 6 on the different backends as you suggested. in fact, i've been thinking of putting mesa as the default backend due to less overhead.

That being said, the `init_agent_loop()` function applies only on osbrain agents.

**Comment by BjoernLudwigPTB** [comment]
#170 is ready to be reviewed and merged I think.

**Comment by BjoernLudwigPTB** [comment]
> [...] i've been thinking of putting mesa as the default backend due to less overhead.

My first question would be, what does osbrain offer, we do not get from Mesa? I personally prefer Mesa especially because of the debugging capability. Let's discuss that later.

**Comment by bangxiangyong** [comment]
osbrain offers real connectivity between agents (each agent has its own port & ip address) in distributed systems (e,g connecting agents from raspberry pis to PCs, etc). which is also why it is hard to debug. 

hence, osbrain is closer to deployment phase, whereas mesa is suited for the simulation/designing phase .

**Comment by BjoernLudwigPTB** [comment]
> osbrain offers real connectivity between agents (each agent has its own port & ip address) in distributed systems (e,g connecting agents from raspberry pis to PCs, etc). which is also why it is hard to debug.
> 
> hence, osbrain is closer to deployment phase, whereas mesa is suited for the simulation/designing phase .

Thanks for the reminder, yes, of course.
