### ISSUE TITLE
Incorporate Ehlimana's Work

### ISSUE THREAD

**Issue by bangxiangyong** [Met4FoF/agentMET4FOF#27]
Incorporate the methods for accounting uncertainty developed by Ehlimana into the agents.

**Comment by BjoernLudwigPTB** [comment]
Somehow of course this would be nice, but due to lack of need, we will close this now. This is more of a nice to have meanwhile, which is why we postpne this to a time, when someone feels, it would be useful again. If you read this and think the time has come, feel free to reopen this issue.

By the way, we meant this repo: https://github.com/harislulic/ZeMA-machine-learning-tutorials
